<?xml version="1.0" encoding="utf-8"?><Database Name="DB_A26F9A_wfm" Class="WFMLiveDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sql5028.smarterasp.net;Initial Catalog=DB_A26F9A_wfm;User ID=DB_A26F9A_wfm_admin" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_A26F9A_wfmConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_assignsupervisor" Member="tbl_assignsupervisors">
    <Type Name="tbl_assignsupervisor">
      <Column Name="AssignSupervisorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SupervisorName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ShiftName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_assignwork" Member="tbl_assignworks">
    <Type Name="tbl_assignwork">
      <Column Name="AssignWorkID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkerName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ShiftName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Checklist" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="WorkTime" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="WorkInterVal" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_attendance" Member="tbl_attendances">
    <Type Name="tbl_attendance">
      <Column Name="AttendanceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_checklist" Member="tbl_checklists">
    <Type Name="tbl_checklist">
      <Column Name="ChecklistID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkInterval" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShiftID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_city" Member="tbl_cities">
    <Type Name="tbl_city">
      <Column Name="CityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="StateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_company" Member="tbl_companies">
    <Type Name="tbl_company">
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyPhone" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CompanyAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OwnerName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="OwnerMobile" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_dailyreporting" Member="tbl_dailyreportings">
    <Type Name="tbl_dailyreporting">
      <Column Name="DailyReportingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ShiftName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Checklist" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_lostfound" Member="tbl_lostfounds">
    <Type Name="tbl_lostfound">
      <Column Name="LostFoundID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FounderName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_organization" Member="tbl_organizations">
    <Type Name="tbl_organization">
      <Column Name="OrgID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrganizationName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Designation" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Logo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_shift" Member="tbl_shifts">
    <Type Name="tbl_shift">
      <Column Name="ShiftID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShiftName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EndTime" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_state" Member="tbl_states">
    <Type Name="tbl_state">
      <Column Name="StateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_stock" Member="tbl_stocks">
    <Type Name="tbl_stock">
      <Column Name="StockID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(10,3)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_tickets" Member="tbl_tickets">
    <Type Name="tbl_ticket">
      <Column Name="TicketID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CompanyEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ccomments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssignWorkerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_worker" Member="tbl_workers">
    <Type Name="tbl_worker">
      <Column Name="WorkerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDProof" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ParmanentAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CurrentAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FatherName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_supervisor" Member="tbl_supervisors">
    <Type Name="tbl_supervisor">
      <Column Name="SupervisorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FatherName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ParmanentAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CurrentAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OrgID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDProof" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Deactivecompany" Method="Deactivecompany">
    <Parameter Name="companyid" Type="System.Int32" DbType="Int" />
    <Parameter Name="orgid" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.WorkAsssignmentReport" Method="WorkAsssignmentReport">
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Company" Parameter="company" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="WorkAsssignmentReportResult">
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkerName" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ShiftName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Checklist" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkTime" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="WorkInterVal" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAssignedWorkData" Method="GetAssignedWorkData">
    <Parameter Name="OrgId" Parameter="orgId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAssignedWorkDataResult">
      <Column Name="WorkerID" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="WorkerName" Type="System.String" DbType="NVarChar(62)" CanBeNull="true" />
      <Column Name="ShiftName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Checklist" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDailyReportingData" Method="GetDailyReportingData">
    <Parameter Name="OrgId" Parameter="orgId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetDailyReportingDataResult">
      <Column Name="WorkerID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkerName" Type="System.String" DbType="NVarChar(62)" CanBeNull="true" />
      <Column Name="ShiftName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Checklist" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetLostFoundData" Method="GetLostFoundData">
    <Parameter Name="OrgId" Parameter="orgId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetLostFoundDataResult">
      <Column Name="LostFoundID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="companyname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WorkerName" Type="System.String" DbType="NVarChar(62)" CanBeNull="true" />
      <Column Name="itemname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="comments" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="date" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>